// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: days.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDay = `-- name: CreateDay :one
INSERT INTO days (reference_date, created_at, updated_at, user_id)
VALUES ($1, $2, $3, $4)
RETURNING reference_date, created_at, updated_at, user_id
`

type CreateDayParams struct {
	ReferenceDate time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	UserID        uuid.UUID
}

func (q *Queries) CreateDay(ctx context.Context, arg CreateDayParams) (Day, error) {
	row := q.db.QueryRowContext(ctx, createDay,
		arg.ReferenceDate,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
	)
	var i Day
	err := row.Scan(
		&i.ReferenceDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteDay = `-- name: DeleteDay :exec
DELETE FROM days
WHERE reference_date=$1
`

func (q *Queries) DeleteDay(ctx context.Context, referenceDate time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteDay, referenceDate)
	return err
}

const getDays = `-- name: GetDays :many
SELECT reference_date, created_at, updated_at, user_id FROM days
WHERE reference_date=$1
`

func (q *Queries) GetDays(ctx context.Context, referenceDate time.Time) ([]Day, error) {
	rows, err := q.db.QueryContext(ctx, getDays, referenceDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Day
	for rows.Next() {
		var i Day
		if err := rows.Scan(
			&i.ReferenceDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
