// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (event_id, created_at, updated_at, event_name, start_time, end_time, reference_date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING event_id, created_at, updated_at, event_name, start_time, end_time, reference_date
`

type CreateEventParams struct {
	EventID       uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	EventName     string
	StartTime     time.Time
	EndTime       time.Time
	ReferenceDate time.Time
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.EventID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.EventName,
		arg.StartTime,
		arg.EndTime,
		arg.ReferenceDate,
	)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventName,
		&i.StartTime,
		&i.EndTime,
		&i.ReferenceDate,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE event_id=$1
`

func (q *Queries) DeleteEvent(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, eventID)
	return err
}
