// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Day struct {
	ReferenceDate time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	UserID        uuid.UUID
}

type Event struct {
	EventID       uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	EventName     string
	StartTime     time.Time
	EndTime       time.Time
	ReferenceDate time.Time
}

type User struct {
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
	Password  string
	Email     string
}
