// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (event_id, created_at, updated_at, event_name, description, recurring, start_time, end_time, day_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING event_id, created_at, updated_at, event_name, description, recurring, start_time, end_time, day_id
`

type CreateEventParams struct {
	EventID     uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	EventName   string
	Description string
	Recurring   int32
	StartTime   time.Time
	EndTime     time.Time
	DayID       uuid.UUID
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.EventID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.EventName,
		arg.Description,
		arg.Recurring,
		arg.StartTime,
		arg.EndTime,
		arg.DayID,
	)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventName,
		&i.Description,
		&i.Recurring,
		&i.StartTime,
		&i.EndTime,
		&i.DayID,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE event_id=$1
`

func (q *Queries) DeleteEvent(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, eventID)
	return err
}

const getEvents = `-- name: GetEvents :many
SELECT event_id, created_at, updated_at, event_name, description, recurring, start_time, end_time, day_id FROM events
WHERE day_id=$1
`

func (q *Queries) GetEvents(ctx context.Context, dayID uuid.UUID) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEvents, dayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventName,
			&i.Description,
			&i.Recurring,
			&i.StartTime,
			&i.EndTime,
			&i.DayID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :exec
UPDATE events
SET updated_at=$2,
    event_name=$3,
    description=$4,
    recurring=$5,
    start_time=$6,
    end_time=$7
WHERE event_id=$1
`

type UpdateEventParams struct {
	EventID     uuid.UUID
	UpdatedAt   time.Time
	EventName   string
	Description string
	Recurring   int32
	StartTime   time.Time
	EndTime     time.Time
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.ExecContext(ctx, updateEvent,
		arg.EventID,
		arg.UpdatedAt,
		arg.EventName,
		arg.Description,
		arg.Recurring,
		arg.StartTime,
		arg.EndTime,
	)
	return err
}
