// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Day struct {
	DayID         uuid.UUID
	ReferenceDate time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	UserID        uuid.UUID
}

type Event struct {
	EventID     uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	EventName   string
	Description string
	Recurring   int32
	StartTime   time.Time
	EndTime     time.Time
	DayID       uuid.UUID
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
	Password  string
	Email     string
}
